"""Add campos de óbito

Revision ID: 3f2150644429
Revises: be2a665c1116
Create Date: 2026-07-24 14:32:04.496406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2150644429'
down_revision = 'be2a665c1116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('militares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_obito', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('causa_obito', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('obs_obito', sa.Text(), nullable=True))
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('militares', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('obs_obito')
        batch_op.drop_column('causa_obito')
        batch_op.drop_column('data_obito')

    # ### end Alembic commands ###
