"""add foto field to Militar

Revision ID: be2a665c1116
Revises: 
Create Date: 2026-06-18 14:36:42.467557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2a665c1116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('militares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('militares', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
